[32m2022-04-20 21:09:29 -0400[0m - dagster - [34mDEBUG[0m - load_data_to_snowflake - 74e8b4b9-7479-47b1-ae2e-c10043355bb2 - 46746 - delete_partition_from_snowflake - LOGS_CAPTURED - Started capturing logs for step: delete_partition_from_snowflake.
[32m2022-04-20 21:09:29 -0400[0m - dagster - [34mDEBUG[0m - load_data_to_snowflake - 74e8b4b9-7479-47b1-ae2e-c10043355bb2 - 46746 - delete_partition_from_snowflake - STEP_START - Started execution of step "delete_partition_from_snowflake".
[32m2022-04-20 21:09:31 -0400[0m - dagster - [34mINFO[0m - resource:snowflake - 74e8b4b9-7479-47b1-ae2e-c10043355bb2 - delete_partition_from_snowflake - Executing query: 
        
        DELETE FROM RAW.RAW_NHL_GAME_DATA
        where partition_date = date('TimeWindow(start=DateTime(2022, 4, 19, 0, 0, 0, tzinfo=Timezone('UTC')), end=DateTime(2022, 4, 20, 0, 0, 0, tzinfo=Timezone('UTC')))')
        
[32m2022-04-20 21:09:32 -0400[0m - dagster - [34mERROR[0m - [31mload_data_to_snowflake - 74e8b4b9-7479-47b1-ae2e-c10043355bb2 - 46746 - delete_partition_from_snowflake - STEP_FAILURE - Execution of step "delete_partition_from_snowflake" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "delete_partition_from_snowflake"::

snowflake.connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
syntax error line 2 at position 102 unexpected 'UTC'.

Stack Trace:
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/core/execution/plan/utils.py", line 47, in solid_execution_error_boundary
    yield
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/utils/__init__.py", line 401, in iterate_with_context
    next_output = next(iterator)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/nhl_elt/assets/s3_to_snowflake.py", line 22, in delete_partition_from_snowflake
    """
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/dagster_snowflake/resources.py", line 106, in execute_query
    cursor.execute(sql, parameters)  # pylint: disable=E1101
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 789, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/snowflake/connector/errors.py", line 277, in errorhandler_wrapper
    error_value,
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/alecryan/Desktop/nhl-analytics-pipleine-dagster/venv/lib/python3.7/site-packages/snowflake/connector/errors.py", line 214, in default_errorhandler
    cursor=cursor,
[0m
